---
services:
  node:
    build: .
    image: ${IMAGE}:${TAG}
    ports: [8000:8000]
    env_file: [.env]
    depends_on: [db]

  # ensure that after using node tools init-db that we change the db host to "db" since it will
  # be accessed within the docker network
  db:
    image: postgres
    restart: always
    environment:
      # must match credentials and configuration used with nodetools
      POSTGRES_PASSWORD: postfiat
      POSTGRES_USER: postfiat
      # the name of the DB matches what is provided to us by node tools init-db
      POSTGRES_DB: postfiat_db_testnet
    ports: [5432:5432]
    volumes: [pgdata:/var/lib/postgresql/data]
volumes:
  pgdata:
